<?php

namespace Database\Seeders;

use App\Models\Destination;
use App\Models\Experience;
use App\Models\Tour;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = Destination::all()->keyBy('slug');
        $experiences = Experience::all()->keyBy('slug');

        $tours = [
            [
                'title' => '7-Day Kenya Classic Explorer',
                'slug' => '7-day-kenya-classic-explorer',
                'short_description' => 'The definitive Kenya safari experience featuring the Big Five in Maasai Mara, flamingos and rhinos at Lake Nakuru, and Mount Kilimanjaro views in Amboseli.',
                'description' => 'Experience the finest wildlife reserves in East Africa on this classic 7-day guided safari. Travel across the Great Rift Valley, marvel at hundreds of bird species and endangered rhinos at Lake Nakuru, witness giant elephant herds in Amboseli beneath Mount Kilimanjaro, and spend 3 unforgettable days in the legendary Maasai Mara tracking lions, leopards, and cheetahs.',
                'duration_days' => 7,
                'duration_nights' => 6,
                'starting_price' => 1850.00,
                'currency' => 'USD',
                'tour_type' => 'both',
                'difficulty' => 'easy',
                'badge' => 'Best Seller',
                'country' => 'Kenya',
                'location_summary' => 'Maasai Mara, Nakuru, Amboseli',
                'hero_image' => 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    'Guaranteed window seat in custom 4x4 Cruiser',
                    'Full board accommodation at premier tented camps',
                    'Big Five game drives across Kenya’s top 3 reserves',
                ],
                'inclusions' => [
                    'All national park entrance and conservation fees',
                    'Private custom 4x4 Land Cruiser with pop-up roof',
                    'Dedicated professional driver-guide',
                    'Full board lodge and luxury camp accommodation',
                    'Complimentary bottled drinking water throughout the safari',
                    'All government taxes and levies',
                ],
                'exclusions' => [
                    'International flights and Kenya Electronic Travel Authorization (eTA)',
                    'Optional hot air balloon safari over the Maasai Mara',
                    'Personal travel and medical insurance',
                    'Tips and gratuities for safari guide and lodge staff',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 1,
                'destinations' => ['amboseli', 'lake-nakuru-naivasha', 'maasai-mara'],
                'experiences' => ['big-five-safaris', 'photography-safaris'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Nairobi to Amboseli National Park',
                        'location' => 'Amboseli National Park',
                        'description' => 'Depart Nairobi early in the morning through the Athi plains towards Amboseli. Arrive in time for lunch at your lodge, followed by an afternoon game drive against the backdrop of Mount Kilimanjaro.',
                        'accommodation' => 'Amboseli Serena Safari Lodge',
                        'meals' => 'Lunch, Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full Day in Amboseli National Park',
                        'location' => 'Amboseli National Park',
                        'description' => 'Full day exploring Amboseli’s swamps and savannah. Spot huge elephant bulls, lions, cheetahs, and over 400 species of birds. Enjoy a scenic picnic lunch atop Observation Hill.',
                        'accommodation' => 'Amboseli Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Amboseli to Lake Nakuru National Park',
                        'location' => 'Lake Nakuru National Park',
                        'description' => 'After breakfast, drive through the Great Rift Valley escarpment to Lake Nakuru. Enjoy an afternoon game drive around the lake, tracking endangered black and white rhinos and Rothschild giraffes.',
                        'accommodation' => 'Sarova Lion Hill Game Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Lake Nakuru to Maasai Mara National Reserve',
                        'location' => 'Maasai Mara',
                        'description' => 'Journey southwest across the floor of the Great Rift Valley into the legendary Maasai Mara. Afternoon game drive in search of lions, leopards, and vast herds of herbivores.',
                        'accommodation' => 'Ashnil Mara Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 5,
                        'title' => 'Full Day Maasai Mara Big Five Safari',
                        'location' => 'Maasai Mara',
                        'description' => 'Full day with picnic lunches in the Mara plains. Track predators on the hunt and explore the Mara Riverbanks inhabited by hippos and giant Nile crocodiles.',
                        'accommodation' => 'Ashnil Mara Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 6,
                        'title' => 'Maasai Mara Exploration & Cultural Village Visit',
                        'location' => 'Maasai Mara',
                        'description' => 'Morning game drive tracking big cats, followed by an authentic afternoon visit to an indigenous Maasai cultural boma to learn about Maasai traditions, dances, and bush survival skills.',
                        'accommodation' => 'Ashnil Mara Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 7,
                        'title' => 'Maasai Mara to Nairobi Departure',
                        'location' => 'Nairobi',
                        'description' => 'Early morning sunrise game drive followed by a hearty breakfast. Drive back to Nairobi arriving in the late afternoon for airport drop-off or onward arrangements.',
                        'accommodation' => 'Departure (Day Room on Request)',
                        'meals' => 'Breakfast',
                    ],
                ],
            ],
            [
                'title' => '5-Day Maasai Mara Migration Safari',
                'slug' => '5-day-maasai-mara-migration-safari',
                'short_description' => 'Immerse yourself into the world\'s most spectacular wildlife event. Unrivaled predator action, river crossings, and endless savannah plains.',
                'description' => 'Focused exclusively on the world-famous Maasai Mara and the Mara Triangle during the peak Great Migration season. Experience intense wildlife encounters as millions of wildebeests and zebras brave predator-filled rivers and sweeping savannahs.',
                'duration_days' => 5,
                'duration_nights' => 4,
                'starting_price' => 1450.00,
                'currency' => 'USD',
                'tour_type' => 'both',
                'difficulty' => 'easy',
                'badge' => 'Great Migration',
                'country' => 'Kenya',
                'location_summary' => 'Maasai Mara & Mara Triangle',
                'hero_image' => 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    'Mara River crossing vantage game drives',
                    'Optional hot air balloon safari experience',
                    'Intense predator action with lions, cheetahs & hyenas',
                ],
                'inclusions' => [
                    'All Maasai Mara park fees and conservation levies',
                    'Private 4x4 Land Cruiser with pop-up roof',
                    '4 Nights luxury tented camp accommodation',
                    'All meals on full board basis',
                    'Services of a dedicated bronze/silver KPSGA guide',
                ],
                'exclusions' => [
                    'International flights',
                    'Optional hot air balloon safari',
                    'Travel insurance',
                    'Driver guide tips',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 2,
                'destinations' => ['maasai-mara'],
                'experiences' => ['great-migration', 'big-five-safaris', 'photography-safaris'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Nairobi to Maasai Mara Reserve',
                        'location' => 'Maasai Mara',
                        'description' => 'Pick up from Nairobi and scenic drive down the Great Rift Valley into the Mara. Afternoon game drive in the reserve.',
                        'accommodation' => 'Mara Serena Safari Lodge',
                        'meals' => 'Lunch, Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Mara River & Crossing Points Safari',
                        'location' => 'Mara Triangle',
                        'description' => 'Full day game drive along the Mara River where wildebeest herds gather to brave the crocodile-infested waters.',
                        'accommodation' => 'Mara Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Plains Predators & Big Cat Tracking',
                        'location' => 'Maasai Mara',
                        'description' => 'Morning and late afternoon game drives focusing on lion prides, cheetah coalitions, and solitary leopards.',
                        'accommodation' => 'Mara Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Full Day Mara Wilderness & Bush Sunset',
                        'location' => 'Maasai Mara',
                        'description' => 'Venture into remote corners of the reserve with a packed bush lunch, concluding with a memorable African sunset.',
                        'accommodation' => 'Mara Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 5,
                        'title' => 'Morning Game Drive & Return to Nairobi',
                        'location' => 'Nairobi',
                        'description' => 'Final morning game drive at sunrise, followed by breakfast and return drive to Nairobi.',
                        'accommodation' => 'Departure',
                        'meals' => 'Breakfast',
                    ],
                ],
            ],
            [
                'title' => '4-Day Amboseli & Giants of Kilimanjaro',
                'slug' => '4-day-amboseli-giants-of-kilimanjaro',
                'short_description' => 'Witness massive tuskers against the snowcapped peaks of Mount Kilimanjaro, combined with the volcanic springs of Tsavo West.',
                'description' => 'A picturesque 4-day journey combining Amboseli National Park with the dramatic volcanic landscapes of Tsavo West. Capture unmatched photographs of elephant families against Mount Kilimanjaro.',
                'duration_days' => 4,
                'duration_nights' => 3,
                'starting_price' => 1150.00,
                'currency' => 'USD',
                'tour_type' => 'both',
                'difficulty' => 'easy',
                'badge' => 'Kilimanjaro Views',
                'country' => 'Kenya',
                'location_summary' => 'Amboseli & Tsavo West',
                'hero_image' => 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    'Iconic Mount Kilimanjaro sunrise photography',
                    'Visit to Mzima Springs underwater hippo observatory',
                    'Large herds of free-ranging African elephants',
                ],
                'inclusions' => [
                    'Amboseli and Tsavo West park entry fees',
                    '4x4 Land Cruiser with pop-up roof',
                    'Full board accommodation',
                    'Expert local guide and unlimited drinking water',
                ],
                'exclusions' => [
                    'International flights',
                    'Personal expenses and tips',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 3,
                'destinations' => ['amboseli'],
                'experiences' => ['big-five-safaris', 'photography-safaris', 'family-safaris'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Nairobi to Amboseli National Park',
                        'location' => 'Amboseli',
                        'description' => 'Scenic transfer from Nairobi to Amboseli. Afternoon game drive enjoying views of Mount Kilimanjaro.',
                        'accommodation' => 'Ol Tukai Lodge Amboseli',
                        'meals' => 'Lunch, Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full Day Amboseli Wildlife Exploration',
                        'location' => 'Amboseli',
                        'description' => 'Morning and afternoon game drives around Lake Amboseli and Enkongo Narok marshes where elephants bathe.',
                        'accommodation' => 'Ol Tukai Lodge Amboseli',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Amboseli to Tsavo West National Park',
                        'location' => 'Tsavo West',
                        'description' => 'Drive through the Shetani lava flow to Tsavo West. Visit Mzima Springs to view hippos through the glass hide.',
                        'accommodation' => 'Kilaguni Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Morning Game Drive & Return to Nairobi',
                        'location' => 'Nairobi',
                        'description' => 'Sunrise game drive in Tsavo West, breakfast, and transfer back to Nairobi.',
                        'accommodation' => 'Departure',
                        'meals' => 'Breakfast',
                    ],
                ],
            ],
            [
                'title' => '10-Day Best of Kenya & Tanzania',
                'slug' => '10-day-best-of-kenya-and-tanzania',
                'short_description' => 'The ultimate East African wildlife circuit: Maasai Mara, Serengeti National Park, and the breathtaking Ngorongoro Crater caldera.',
                'description' => 'The crowning safari adventure across two premier wildlife nations. Travel seamlessly between Kenya\'s Maasai Mara and Tanzania\'s vast Serengeti, culminating at the UNESCO World Heritage Ngorongoro Crater.',
                'duration_days' => 10,
                'duration_nights' => 9,
                'starting_price' => 3650.00,
                'currency' => 'USD',
                'tour_type' => 'private',
                'difficulty' => 'moderate',
                'badge' => 'Grand Expedition',
                'country' => 'Kenya & Tanzania',
                'location_summary' => 'Kenya & Tanzania Combined',
                'hero_image' => 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    'Seamless cross-border safari transfer & flights',
                    'Ngorongoro Crater floor 6-hour safari descent',
                    'Maasai Mara and Serengeti back-to-back',
                ],
                'inclusions' => [
                    'All Kenya and Tanzania national park fees',
                    'Ngorongoro Crater vehicle service fee',
                    'Private 4x4 Land Cruiser with open pop-up roof',
                    'Full board luxury lodge accommodation',
                    'Internal cross-border logistics assistance',
                ],
                'exclusions' => [
                    'International flights and visas for Kenya & Tanzania',
                    'Tips and personal items',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 4,
                'destinations' => ['maasai-mara', 'serengeti-ngorongoro'],
                'experiences' => ['big-five-safaris', 'great-migration', 'honeymoon-safaris'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Arrival in Nairobi',
                        'location' => 'Nairobi',
                        'description' => 'Arrive at Jomo Kenyatta International Airport, meet your Gentriiq Safaris & Tours director, and transfer to your luxury boutique hotel.',
                        'accommodation' => 'Hemingways Nairobi',
                        'meals' => 'Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Nairobi to Maasai Mara',
                        'location' => 'Maasai Mara',
                        'description' => 'Flight or overland drive to the Maasai Mara. Afternoon game drive in the Mara reserve.',
                        'accommodation' => 'Governor’s Camp Mara',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Full Day Maasai Mara',
                        'location' => 'Maasai Mara',
                        'description' => 'Extensive game viewing across the Mara plains tracking big cats and migrating herds.',
                        'accommodation' => 'Governor’s Camp Mara',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Maasai Mara to Serengeti National Park',
                        'location' => 'Serengeti',
                        'description' => 'Cross the Kenya-Tanzania border with assisted clearance and enter the legendary Serengeti plains.',
                        'accommodation' => 'Serengeti Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 5,
                        'title' => 'Full Day Serengeti Big Cat Safari',
                        'location' => 'Serengeti',
                        'description' => 'Explore the Seronera Valley and rocky kopjes where leopards and lions take shelter.',
                        'accommodation' => 'Serengeti Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 6,
                        'title' => 'Serengeti to Ngorongoro Conservation Area',
                        'location' => 'Ngorongoro',
                        'description' => 'Drive through Olduvai Gorge towards the rim of the great Ngorongoro Crater.',
                        'accommodation' => 'Ngorongoro Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 7,
                        'title' => 'Ngorongoro Crater Floor Safari',
                        'location' => 'Ngorongoro Crater',
                        'description' => 'Descend 600 meters to the crater floor for a 6-hour game drive encountering black rhinos, flamingo-filled soda lakes, and dense lion prides.',
                        'accommodation' => 'Ngorongoro Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 8,
                        'title' => 'Ngorongoro to Lake Manyara National Park',
                        'location' => 'Lake Manyara',
                        'description' => 'Game drive in Lake Manyara, known for tree-climbing lions and dense baboon troops.',
                        'accommodation' => 'Lake Manyara Serena Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 9,
                        'title' => 'Lake Manyara to Tarangire National Park',
                        'location' => 'Tarangire',
                        'description' => 'Explore the baobab-studded landscapes and giant elephant herds of Tarangire.',
                        'accommodation' => 'Tarangire Safari Lodge',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 10,
                        'title' => 'Tarangire to Arusha & Kilimanjaro Airport',
                        'location' => 'Arusha',
                        'description' => 'Morning game drive, transfer to Arusha for farewell lunch, and drop-off at Kilimanjaro International Airport.',
                        'accommodation' => 'Departure',
                        'meals' => 'Breakfast, Lunch',
                    ],
                ],
            ],
            [
                'title' => '3-Day Samburu Rugged Frontier',
                'slug' => '3-day-samburu-rugged-frontier',
                'short_description' => 'Discover the Samburu Special 5: Grevy\'s zebra, Somali ostrich, reticulated giraffe, gerenuk, and beisa oryx along the Ewaso Nyiro river.',
                'description' => 'Head into Kenya’s semi-arid northern frontier. Samburu offers an utterly distinct safari atmosphere characterized by doum palms, rugged hills, and unique wildlife species found nowhere else south of the equator.',
                'duration_days' => 3,
                'duration_nights' => 2,
                'starting_price' => 890.00,
                'currency' => 'USD',
                'tour_type' => 'both',
                'difficulty' => 'easy',
                'badge' => 'Northern Wilderness',
                'country' => 'Kenya',
                'location_summary' => 'Samburu & Buffalo Springs',
                'hero_image' => 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    'Encounter rare wildlife found only in the North',
                    'Authentic Samburu warrior cultural experience',
                    'Ewaso Nyiro river elephant viewing',
                ],
                'inclusions' => [
                    'Samburu national reserve conservation fees',
                    '4x4 Land Cruiser with pop-up roof',
                    'Full board lodge accommodation',
                    'Professional safari naturalist guide',
                ],
                'exclusions' => [
                    'International flights',
                    'Gratuities and personal drinks',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 5,
                'destinations' => ['samburu'],
                'experiences' => ['big-five-safaris', 'cultural-tours'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Nairobi to Samburu Game Reserve',
                        'location' => 'Samburu',
                        'description' => 'Scenic drive north past Mount Kenya and the Equator into Samburu. Afternoon game drive along the river.',
                        'accommodation' => 'Samburu Intrepids Camp',
                        'meals' => 'Lunch, Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full Day Samburu Special 5 Exploration',
                        'location' => 'Samburu',
                        'description' => 'Full day tracking Grevy’s zebras, reticulated giraffes, gerenuks, beisa oryx, and predators. Evening cultural exchange.',
                        'accommodation' => 'Samburu Intrepids Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'Samburu to Nairobi Return',
                        'location' => 'Nairobi',
                        'description' => 'Morning game drive at sunrise, breakfast, and journey back to Nairobi.',
                        'accommodation' => 'Departure',
                        'meals' => 'Breakfast',
                    ],
                ],
            ],
            [
                'title' => '8-Day Bush to Beach Luxury Escape',
                'slug' => '8-day-bush-to-beach-luxury-escape',
                'short_description' => 'Thrilling safari game drives in Maasai Mara followed by direct flight to the pristine white sands and turquoise waters of Diani Beach.',
                'description' => 'The ultimate Kenyan combination. Spend 4 thrilling days exploring the Maasai Mara savannah tracking Big Cats, then board an internal flight directly to the coral sands and tranquil warm waters of Diani Beach on the Swahili Coast.',
                'duration_days' => 8,
                'duration_nights' => 7,
                'starting_price' => 2450.00,
                'currency' => 'USD',
                'tour_type' => 'private',
                'difficulty' => 'easy',
                'badge' => 'Bush & Beach',
                'country' => 'Kenya',
                'location_summary' => 'Maasai Mara & Diani Beach',
                'hero_image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
                'highlights' => [
                    '4 Days Big Five game viewing + 4 Days beach resort',
                    'Direct internal bush-to-beach flight included',
                    'Pristine private beachfront resort in Diani',
                ],
                'inclusions' => [
                    'Maasai Mara park entry fees and safari Cruiser',
                    'Internal flight from Maasai Mara airstrip to Diani Beach / Ukunda',
                    '4 Nights luxury tented camp (full board)',
                    '3 Nights 5-star beachfront resort (half board)',
                    'All airport and airstrip transfers',
                ],
                'exclusions' => [
                    'International flights',
                    'Motorized watersports and diving',
                    'Tips and personal items',
                ],
                'featured' => true,
                'status' => 'published',
                'published_at' => now(),
                'sort_order' => 6,
                'destinations' => ['maasai-mara', 'diani-zanzibar'],
                'experiences' => ['bush-to-beach', 'honeymoon-safaris', 'big-five-safaris'],
                'days' => [
                    [
                        'day_number' => 1,
                        'title' => 'Nairobi to Maasai Mara',
                        'location' => 'Maasai Mara',
                        'description' => 'Travel to Maasai Mara and embark on your initial afternoon safari.',
                        'accommodation' => 'Neptune Mara Rianta Luxury Camp',
                        'meals' => 'Lunch, Dinner',
                    ],
                    [
                        'day_number' => 2,
                        'title' => 'Full Day Mara Predator Game Drive',
                        'location' => 'Maasai Mara',
                        'description' => 'Sunrise to sunset game drives across the open plains with packed picnic lunch.',
                        'accommodation' => 'Neptune Mara Rianta Luxury Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 3,
                        'title' => 'River Crossings & Mara Triangle',
                        'location' => 'Maasai Mara',
                        'description' => 'Explore the Mara River banks and escarpment.',
                        'accommodation' => 'Neptune Mara Rianta Luxury Camp',
                        'meals' => 'Breakfast, Lunch, Dinner',
                    ],
                    [
                        'day_number' => 4,
                        'title' => 'Morning Game Drive & Fly to Diani Beach',
                        'location' => 'Diani Beach',
                        'description' => 'Morning game drive, then transfer to the bush airstrip for your direct flight to Ukunda / Diani Beach. Check in to your luxury oceanfront resort.',
                        'accommodation' => 'The Sands at Nomad / Swahili Beach Resort',
                        'meals' => 'Breakfast, Dinner',
                    ],
                    [
                        'day_number' => 5,
                        'title' => 'Relaxation on Diani Beach',
                        'location' => 'Diani Beach',
                        'description' => 'Unwind on the soft white sands, swim in the warm Indian Ocean, or indulge in resort spa treatments.',
                        'accommodation' => 'The Sands at Nomad / Swahili Beach Resort',
                        'meals' => 'Breakfast, Dinner',
                    ],
                    [
                        'day_number' => 6,
                        'title' => 'Marine Excursion & Dhow Sunset Cruise',
                        'location' => 'Diani Beach',
                        'description' => 'Optional snorkeling at Kisite-Mpunguti Marine Park and evening traditional dhow sunset cruise.',
                        'accommodation' => 'The Sands at Nomad / Swahili Beach Resort',
                        'meals' => 'Breakfast, Dinner',
                    ],
                    [
                        'day_number' => 7,
                        'title' => 'Coastal Serenity in Diani',
                        'location' => 'Diani Beach',
                        'description' => 'Full day leisure on the coast enjoying tropical fruits, ocean views, and warm Swahili hospitality.',
                        'accommodation' => 'The Sands at Nomad / Swahili Beach Resort',
                        'meals' => 'Breakfast, Dinner',
                    ],
                    [
                        'day_number' => 8,
                        'title' => 'Transfer to Mombasa / Nairobi & Departure',
                        'location' => 'Nairobi / Mombasa',
                        'description' => 'Transfer to Moi International Airport Mombasa or flight to Nairobi for your homebound flight.',
                        'accommodation' => 'Departure',
                        'meals' => 'Breakfast',
                    ],
                ],
            ],
        ];

        foreach ($tours as $tourData) {
            $destSlugs = $tourData['destinations'] ?? [];
            $expSlugs = $tourData['experiences'] ?? [];
            $days = $tourData['days'] ?? [];

            unset($tourData['destinations'], $tourData['experiences'], $tourData['days']);

            $tour = Tour::updateOrCreate(
                ['slug' => $tourData['slug']],
                $tourData
            );

            // Sync Destinations
            $destIds = Destination::whereIn('slug', $destSlugs)->pluck('id');
            $tour->destinations()->sync($destIds);

            // Sync Experiences
            $expIds = Experience::whereIn('slug', $expSlugs)->pluck('id');
            $tour->experiences()->sync($expIds);

            // Recreate Tour Days
            $tour->days()->delete();
            foreach ($days as $dayData) {
                $tour->days()->create($dayData);
            }
        }
    }
}
